### ISSUE TITLE
Property ID's Don't Match

### ISSUE THREAD

**Issue by akibiaons** [akibiaons/memphisturnkeyrentals#27]
When clicking on a specific marker, only the image correlates with the actual street name, price, beds, baths, and other data stays the same which gives users the wrong info if they are on mobile. So we gotta find a way to assign the data to it's specific property

**Comment by gualberto2** [comment]
This sounds like a strapi issue, ensure that you dont have anything misconfigured that would associate the image as the actual listing. the lsiting should be its own entity with its own id and within that would be an object
