### ISSUE TITLE
Desktop UI

### ISSUE THREAD

**Issue by akibiaons** [akibiaons/memphisturnkeyrentals#28]
/listing and /buildtorent desktop UI sidebar looks like ass and requires that you do an awkwardly swipe with the mouse in order to open up all the property cards, probally due to the mobile handleSmooth animations being triggered and compressing the cards.

**Comment by gualberto2** [comment]
Try using shadcn/sheet or shadcn/dialog instead

**Comment by akibiaons** [comment]
FIXED!!! See PR #31
